# Generated by Django 2.2.5 on 2019-10-15 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='User',
        ),
    ]
